### ISSUE TITLE
Setting develepment:true crashes the process

### ISSUE THREAD

**Issue by fotisp** [punkave/apostrophe-browserify#1]
Hello,

As per the documentation setting development:true will recompile assets upon modification. At the moment this configuration in data/local.js

```
  // This follows the same format as the modules we declare in app.js. You would
  // do it here in order to keep sensitive data like keys and secrets out of your git repo.
  // Note: if you plan on using twitter, don't forget to include the apostrophe-twitter module
  // in app.js!
  //
  modules: {
    'apostrophe-browserify': {
      files: ["./public/js/modules/_site.js"],
      // When this is true `watchify` will recompile your
      // assets any time they are saved. Defaults to `false`.
      development: true,

      // When this is true and `development` is also true
      // watchify will log a message in the console each
      // time your bundle is recompiled. Defaults to `true`.
      verbose: true

    }
  },
```

Causes this error

```
/tmp/apostrophe-sandbox > node app.js 
Watchify is running.
Ran initial Browserify asset bundling.
Apostrophe Sandbox is running in development.
I see no data/address file, defaulting to address 0.0.0.0
I see no data/port file, defaulting to port 3000
Listening on 0.0.0.0:3000

undefined:0


TypeError: undefined is not a function

```

**Comment by kylestetz** [comment]
Thanks @fotisp, I'll look into this today.

**Comment by kylestetz** [comment]
I looked into this and it was not an issue with `apostrophe-browserify`, but rather an issue with `apostrophe-sandbox`. It was including an older version of `watchify` (v0.10) as a dependency and then requiring it in `app.js`, which caused `apostrophe-browserify` to use the old version instead of its more-up-to-date v2.3 dependency.

Here are the changes I made to the sandbox, which, if made to your project, should solve the issue: https://github.com/punkave/apostrophe-sandbox/commit/6c7c8dc42735aa76a136ffe2b417f9df375cf0d5
